---
title: "Data Manipulation"
author: "Evangeline Reynolds"
date: "February 2020"
output: 
  html_document:
    theme: yeti
    highlight: monochrome
---


# The very basics

### [Arithmetic operations, value types, and data structures](arithmetic_and_data_types.html){target="_blank"}

This section cover some very basics including:

- *value types*: numeric,    character,    integer,   date, logical,   factor 

- *arithmetic operators*: `+ `  `-`   `/`   `()` `^ `   

- *data structures*: scalar, vector, matrix, data frame (with rows and columns)

- *functions*: `mean()`, `median()`, `mode()`, `log10()`

- *objects and assignment*: `=` `<-` `->` 

# Data manipulation with the tidyverse

The `{tidyverse}`  data manipulation functions have been a boon to analysts' productivity. This resource is built with the idea that we sometimes just need to see how functions work in action to understand them; just link the materials for each section to see the functions "in-action". The materials here can be used as an introduction or for reference. The `{tidyverse}` is an open source project in R lead by Hadley Wickham; the `{tidyverse}` itself contains several packages designed to work together in a consistent, logical, and human-friendly fashion.

### [One-stream data manipulation](one_stream_wrangle.html#3){target="_blank"}

|function |action |
| :--- | ---: |
| filter()    | *keep rows (if true)*|
| select()    | *keep variables (or drop them `-`var)*|
| mutate()    | *create a new variable*|
| case_when() | *is used for "recoding" variable, often used with mutate()*|
| rename()    | *renaming variables*|
| arrange()   | *order rows based on a variable*|
| slice()     | *keep or drop rows based on row number |


#### [Logical operators](booleans.html#3){target="_blank"}

Especially in filtering, you are likely to use Boolean operatores `==`, `!=`, `>`, `<`, `>=`, `<=`, which make a comparison and return `TRUE` or `FALSE`.  These can also be combine with `&` (both conditions must be met), `|` (either condition may be met), or `%in%` (if the left hand side element is found *among* the right hand side elements, `TRUE` is returned).


### [Summarizing](summarize.html#3){target="_blank"}

You may be interested in summaries of variables in your data --- or perhaps knowing the summaries for variables within different groups. 

|function |action |
| :--- | ---: |
| summarize() | *summarize the data, by groups if they have been declared*|
| group_by()  | *declare subsets in data*|
| distinct()  | *returns only rows that are unique*| 
| tally() & count()     | *counting (by groups if group_by() applied)*|


Base-R functions that you are might use in summarizing include `mean()`, `median()`, `sd()`, `IQR()`, `min()`, `max()` etc.

The function `summary()` can also be used to request summary statistcs for an entire data set. 

### [Shape transformation (wide <---> long)](long_to_wide_and_back.html#3){target="_blank"}

|function |action |
| :--- | ---: |
| gather() *or* pivot_longer() | *from wide to long*|
| spread() *or* pivot_wider() | *from long to wide*|


### [Bringing streams together: Joins and Binds](joining_data.html){target="_blank"}

|function |action |
| :--- | ---: |
| full_join() | *keeps all rows*|
| inner_join()  | *keeps overlapping rows*|
| left_join()  | *keeps all left-hand side rows*| 
| right_join()     | *keeps all right-hand side rows*|
| anti_join()     | *removes rows if there is a match on right-hand side*|
| crossing()    | *for each left-hand side row, include the entire data set of the right-hand side*|
| bind_rows()   |  *stack datasets, finding consistent column names* |
| bind_cols()   |  *glue datasets together side-by-side* |




## [Manipulation with data.table](data.table.html){target="_blank"}


{data.table} is data manipulation package.  It's "blazing fast" and very popular; but this section is under construction --- so limited in its examples. 

## [Manipulation with base R and logical indexing](logical_indexing.html){target="_blank"}

You can also do a lot of data manipulation without any external packages at all.

## [Data Cleaning Examples & Intro to String Manipulation, Country Identifiers, and Date Manipulation](https://evamaerey.github.io/data_manipulation/data_cleaning/data_cleaning){target="_blank"}

What's the workflow from reading in data to analysis ready.  It really depends!  Data cleaning is chard to teach because data can be messy/untidy in a lot of different ways.  The data cleaning flipbook will walk you through some real-life examples, with special focus on string manipulation, country codes and date manipulation.  

- Regular expressions, character string manipulation with `{stringr}`
- Unique identifiers for countries with `{countrycode}`
- Date manipulation with `{lubridate}`


## [Back to "The R Flipbook Textbook" Table of Contents](https://evamaerey.github.io/flipbooks/textbook)

You might also be interested related tools for data visualization and statistical analysis. 
