---
title: "data.table"
author: "Gina Reynolds, July 2019"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=F}
knitr::opts_chunk$set(fig.width = 6, message = F, warning = F, 
                      comment = "", cache = F)
```



---

# Set up

Okay. Let's load the the `BREAK for xaringan` functions for "flipbooking" and the `data.table`.

```{r}
# source(file = "https://raw.githubusercontent.com/EvaMaeRey/little_flipbooks_library/master/xaringan_reveal_parentheses_balanced.R")
library(flipbookr)
```


# Where we are headed 

```{r pipe_data.table, echo = F, eval = T, fig.height=5}
library(data.table)
library(gapminder)
library(magrittr)
library(ggplot2)
gapminder %>% 
  data.table() %>% 
   .[year > 1980] %>% 
   .[                       , 
     mean(gdpPercap)        , 
     by = .(continent, year) ] %>% 
  ggplot() +
  aes(x = year) +
  aes(y = V1) + 
  labs(y = "Average GDP per cap") +
  geom_point() +
  geom_line() +
  aes(color = continent)
```

---

# The pipeline 

---

`r chunk_reveal("pipe_data.table")`



---

```{r walk_through, echo = F, eval = F}
gapminder %>% #BREAK
  data.table() %>% #BREAK
  .[continent == "Asia", ] %>% #BREAK
  .[1:30,] %>% #BREAK
  .[, c(1,3:6)] %>% #BREAK
  .[, .(pop, year, gdpPercap)] %>% #BREAK
  # .[, .(world_pop = sum(pop)), by = year] %>% 
  .[, gdp := gdpPercap * pop] %>% 
  .[year %in% 1952:1967, my_var := 2] %>% 
  .[] %>% #BREAK
  .[, year := NULL] %>% 
  .[]   #BREAK
```


`r chunk_reveal("walk_through", break_type = "user")`


---


# Create a data.table



```{r}
data.table(a = c(1, 2), 
           b = c("a", "b"))
```

---

```{r}
gapminder %>% #BREAK
  data.table() ->
gapminder_dt
```



---

# Subset rows using i

```{r}
gapminder_dt %>% 
  .[1:25, ] %>% 
  .[year > 1980, ]
```

---

# Manipulate columns with j

```{r}
gapminder_dt %>% 
  .[, c(1,3:6)] %>% #BREAK
  .[, .(pop, year, gdpPercap)] 
```

---

# Summarize

```{r}
gapminder_dt %>% 
  .[, .(x = sum(pop))] 
```

---

# COMPUTE COLUMNS


```{r}
knitr::opts_chunk$set(eval = F)
```


```{r}
gapminder_dt[, c := 1 + 2] 
gapminder_dt[a == 1, c := 1 + 2] 
gapminder_dt[, `:=`(c = 1 , d = 2)]
```





```{r}
data.table(a = c(1, 2, 5, 11), 
           b = c("a", "b", "d", "x"),
           c = 1:4) ->
  dt
```


```{r}
dt %>% 
  .[1:2, ] %>% 
  .[a > 1, ]
```

```{r}
dt %>% 
  .[, c(2)]  %>% 
  .[, .(b, c)] 
```


```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 80%}
```


