---
title: "the logic of logical indexing and data wrangling with base R"
author: "Gina Reynolds, September 2019"
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---






class: left, top, inverse
background-image: url(https://images.unsplash.com/photo-1546198632-9ef6368bef12?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80)
background-size: cover

# .large[logical indexing]
### Walk through <br>with {flipbookr}<br>and {xaringan}

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

#### .right[Gina Reynolds<br>Photo Credit: Denny Müller]




```{r setup, include=F}
knitr::opts_chunk$set(fig.width = 8, message = F, warning = F, 
                      comment = "", cache = F)
library(flipbookr)
```


---

# Data wrangling with dplyr and tidyr


```{r}
library(magrittr)
library(gapminder)
```


---

```{r load_packages_manipulation, echo = F, eval = F}
gm_2002 <- gapminder %>% 
  .[, c("year", "country", 
        "pop", "gdpPercap")] %>% 
  .[gapminder$year == 2002, ] %>% 
  .[, -1]

gm_2002$gdp <- with(gm_2002, pop * gdpPercap)
```

`r chunk_reveal("load_packages_manipulation", left_assign = T)`

---


```{r free_form, echo = F, eval = F}
my_data <- 18:1 %>% 
  .[c(1,10,18)] %>% 
  data.frame(y = rep("hi", 3),
             q = 1:3,
             hi = 7:9) %>% 
  .[2:3, ]

names(my_data)[1] <- "var1"
```

`r chunk_reveal("free_form", left_assign = T)`



```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 60%}

@media print {
  .has-continuation {
    display: block;
  }
}
```


