---
title: "summarize"
subtitle: "made with flipbookr and xaringan"
author: "Gina Reynolds, January 2020"
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---




class: left, top, inverse
background-image: url(https://images.unsplash.com/photo-1586255527818-8ad7e579c49c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)
background-size: cover

# .large[Summarizing]
### Walk-throughs <br>with {flipbookr}<br>and {xaringan}

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

#### .right[Gina Reynolds<br>Photo Credit: Zoya Loonohod]






```{r, include = F}
knitr::opts_chunk$set(cache = F, comment = "")
```


---

```{r}
library(gapminder)
library(tidyverse)
```


---

`r flipbookr::chunk_reveal("a_few_more")`

```{r a_few_more, include = F}
gapminder %>% 
  mutate(num_rows = n()) ->
gap_n

# a pipeline to count the number 
# of observations by group
gapminder %>%
  distinct(country, continent) %>% 
  # tally and count are the same
  count(continent) %>% 
  rename(num_countries = n) ->
count_in_continents

# alternatively use n function
gapminder %>% 
  distinct(country, continent) %>% 
  # tally and count are the same
  group_by(continent) %>% 
  summarise(num_countries = n()) ->
count_in_continents
```  

---


`r flipbookr::chunk_reveal("more")`

```{r more, include = F}
# a pipeline to create overall 
# variable summaries
gapminder %>%
  filter(year == 2002) %>% 
  summarize(
    mean_life_exp = mean(lifeExp),
    median_life_exp = median(lifeExp)) ->
overall_summaries_2002

# a pipeline to create groupwise
# variable summaries
gapminder %>%
  filter(year == 2002) %>% 
  group_by(continent) %>% 
  summarize(
    mean_life_exp = mean(lifeExp),
    median_life_exp = median(lifeExp)) ->
summaries_by_continent_2002

# coming soon in a new version of dplyr
# gapminder %>% 
#   group_by(continent) %>% 
#   summarize(across(lifeExp:pop, mean))
```



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 85%}

@media print {
  .has-continuation {
    display: block;
  }
}

```
